name: Grunt

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      
    - name: Install dependencies
      run: |
        npm install --save-dev

    #- name: Generate documentation
    #  run: npm run doc
      
    - name: Grunt test
      run: grunt test
